version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  nginx:
    image: nginx
    ports:
      - 80:80
    environment:
      NGINX_HOST: postgres
      NGINX_PORT: 5432